# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de4e044242311c5cca193055b82726bab4685205727e791f4d19e03312e4d13efa3af40395ec7a167d9e6d02aaf9bf45458d0fc8f7546fb255335ecf4efeb311

test:
  secret_key_base: 89192bb231559f59a0edd272f899c8d8e398ffda2268bca7c82840dc0b37f93d4a3b2e2697871d037e6a8e19c02ae6125617ba9cabb4a94bf7eadfed1689b14c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
